# Generated by Django 5.1.1 on 2024-10-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
